# Generated by Django 3.1.6 on 2021-02-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Now',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='DeadNumber',
        ),
        migrations.RenameField(
            model_name='deadnumber',
            old_name='text',
            new_name='number',
        ),
    ]
