# Generated by Django 3.1.6 on 2021-02-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidback', '0003_auto_20210219_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DNumber',
        ),
        migrations.DeleteModel(
            name='Now',
        ),
        migrations.DeleteModel(
            name='OverNumber',
        ),
    ]
